import Link from 'next/link';
import { Bot, Github, Twitter, Linkedin } from 'lucide-react';

export default function Footer() {
  return (
    <footer className="bg-gray-900 text-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
          <div className="col-span-1 md:col-span-2">
            <div className="flex items-center space-x-2 mb-4">
              <Bot className="h-8 w-8 text-primary-400" />
              <span className="text-xl font-bold">AI News Hub</span>
            </div>
            <p className="text-gray-300 mb-4 max-w-md">
              Your premier destination for AI news written by AI authors and curated summaries 
              from leading AI companies. Stay informed about the latest developments in artificial intelligence.
            </p>
            <div className="flex space-x-4">
              <a href="#" className="text-gray-400 hover:text-white transition-colors">
                <Twitter className="h-5 w-5" />
              </a>
              <a href="#" className="text-gray-400 hover:text-white transition-colors">
                <Github className="h-5 w-5" />
              </a>
              <a href="#" className="text-gray-400 hover:text-white transition-colors">
                <Linkedin className="h-5 w-5" />
              </a>
            </div>
          </div>

          <div>
            <h3 className="text-sm font-semibold text-gray-300 uppercase tracking-wider mb-4">
              Categories
            </h3>
            <ul className="space-y-2">
              <li><Link href="/categories/machine-learning" className="text-gray-400 hover:text-white transition-colors">Machine Learning</Link></li>
              <li><Link href="/categories/ai-industry" className="text-gray-400 hover:text-white transition-colors">AI Industry</Link></li>
              <li><Link href="/categories/research" className="text-gray-400 hover:text-white transition-colors">Research</Link></li>
              <li><Link href="/categories/ethics-policy" className="text-gray-400 hover:text-white transition-colors">Ethics & Policy</Link></li>
              <li><Link href="/categories/applications" className="text-gray-400 hover:text-white transition-colors">Applications</Link></li>
            </ul>
          </div>

          <div>
            <h3 className="text-sm font-semibold text-gray-300 uppercase tracking-wider mb-4">
              Company
            </h3>
            <ul className="space-y-2">
              <li><Link href="/about" className="text-gray-400 hover:text-white transition-colors">About</Link></li>
              <li><Link href="/authors" className="text-gray-400 hover:text-white transition-colors">AI Authors</Link></li>
              <li><Link href="/privacy" className="text-gray-400 hover:text-white transition-colors">Privacy Policy</Link></li>
              <li><Link href="/terms" className="text-gray-400 hover:text-white transition-colors">Terms of Service</Link></li>
            </ul>
          </div>
        </div>

        <div className="mt-8 pt-8 border-t border-gray-800">
          <p className="text-center text-gray-400">
            © 2024 AI News Hub. All rights reserved. Content generated by AI authors.
          </p>
        </div>
      </div>
    </footer>
  );
}